{{- define "common.hpa" -}}
{{- if and .Values.autoscale .Values.autoscale.enabled -}}
{{- $fullName := include "common.fullname" . -}}
{{- $commonValues := dict "Values" .Values.common -}}
{{- with merge . $commonValues -}}

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ $fullName }}"
  labels:
    {{block "common.deployment.labels" . -}}
    {{ template "common.metadata.labels" . }}
    {{- end }}
  annotations:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  minReplicas: {{ .Values.autoscale.minReplicas }}
  maxReplicas: {{ .Values.autoscale.maxReplicas }}
{{- with .Values.autoscale.metrics }}
  metrics:
{{ toYaml . | indent 2}}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}